
package no.nav.arbeidsgiver.notifikasjon.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "NotificationAgencyExternalBasicSF", targetNamespace = "http://www.altinn.no/services/ServiceEngine/Notification/2010/10", wsdlLocation = "file:/Users/g161400/dev/git/arbeidsgiver-notifikasjon-produsent-api/app/src/main/resources/wsdl/NotificationAgencyExternalBasic.svc.wsdl")
public class NotificationAgencyExternalBasicSF
    extends Service
{

    private final static URL NOTIFICATIONAGENCYEXTERNALBASICSF_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONAGENCYEXTERNALBASICSF_EXCEPTION;
    private final static QName NOTIFICATIONAGENCYEXTERNALBASICSF_QNAME = new QName("http://www.altinn.no/services/ServiceEngine/Notification/2010/10", "NotificationAgencyExternalBasicSF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/g161400/dev/git/arbeidsgiver-notifikasjon-produsent-api/app/src/main/resources/wsdl/NotificationAgencyExternalBasic.svc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONAGENCYEXTERNALBASICSF_WSDL_LOCATION = url;
        NOTIFICATIONAGENCYEXTERNALBASICSF_EXCEPTION = e;
    }

    public NotificationAgencyExternalBasicSF() {
        super(__getWsdlLocation(), NOTIFICATIONAGENCYEXTERNALBASICSF_QNAME);
    }

    public NotificationAgencyExternalBasicSF(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONAGENCYEXTERNALBASICSF_QNAME, features);
    }

    public NotificationAgencyExternalBasicSF(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONAGENCYEXTERNALBASICSF_QNAME);
    }

    public NotificationAgencyExternalBasicSF(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONAGENCYEXTERNALBASICSF_QNAME, features);
    }

    public NotificationAgencyExternalBasicSF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationAgencyExternalBasicSF(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns INotificationAgencyExternalBasic
     */
    @WebEndpoint(name = "BasicHttpBinding_INotificationAgencyExternalBasic")
    public INotificationAgencyExternalBasic getBasicHttpBindingINotificationAgencyExternalBasic() {
        return super.getPort(new QName("http://www.altinn.no/services/ServiceEngine/Notification/2010/10", "BasicHttpBinding_INotificationAgencyExternalBasic"), INotificationAgencyExternalBasic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns INotificationAgencyExternalBasic
     */
    @WebEndpoint(name = "BasicHttpBinding_INotificationAgencyExternalBasic")
    public INotificationAgencyExternalBasic getBasicHttpBindingINotificationAgencyExternalBasic(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.altinn.no/services/ServiceEngine/Notification/2010/10", "BasicHttpBinding_INotificationAgencyExternalBasic"), INotificationAgencyExternalBasic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONAGENCYEXTERNALBASICSF_EXCEPTION!= null) {
            throw NOTIFICATIONAGENCYEXTERNALBASICSF_EXCEPTION;
        }
        return NOTIFICATIONAGENCYEXTERNALBASICSF_WSDL_LOCATION;
    }

}
