###
POST https://fakedings.intern.dev.nav.no/fake/custom
Content-Type: application/x-www-form-urlencoded

azp=dev-gcp:fager:notifikasjon-test-produsent&aud=produsent-api

> {%
    client.global.set("auth_token", response.body);
%}

###
POST http://localhost:8081/api/graphql
Content-Type: application/json
Host: ag-notifikasjon-produsent-api.local
Authorization: Bearer {{auth_token}}

{
  "query": "query { whoami  }"
}

###
POST https://ag-notifikasjon-produsent-api.intern.dev.nav.no/api/graphql
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "query": "query { whoami }"
}



