###
POST https://fakedings.dev-gcp.nais.io/fake/custom
Content-Type: application/x-www-form-urlencoded

sub=someproducer&aud=produsent-api

> {%
    client.global.set("auth_token", response.body);
%}

###
POST https://arbeidsgiver-notifikasjon-produsent-api.dev.nav.no/api/graphql
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "query": "query { ping }"
}

###
GET https://arbeidsgiver-notifikasjon-produsent-api.dev.nav.no/api/ide
Authorization: Bearer {{auth_token}}


