###
POST http://localhost:8080/api/graphql
content-type: application/json
Authorization: Bearer {{auth_token}}

{
"query": "query { ping }"
}

###
POST http://localhost:8080/api/graphql
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "query": " { __schema { queryType { name } } }"
}