apiVersion: nais.io/v1alpha1
kind: Naisjob
metadata:
  name: notifikasjon-bigquery-exporter-2
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  schedule: "0 1 * * *"
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-dev
  gcp:
    bigQueryDatasets:
      - name: notifikasjon
        permission: READWRITE