apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  ingresses:
    - https://ag-notifikasjon-produsent-api.intern.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 2
    max: 8
  prometheus:
    enabled: true
    path: /internal/metrics
  accessPolicy:
    inbound:
      rules:
        - application: notifikasjon-test-produsent

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: prod-fss

  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: produsent-model
            envVarPrefix: DB
        autoBackupHour: 1
        maintenance:
          hour: 3
  envFrom:
    - secret: notifikasjon-produsent-api-secrets