apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-skedulert-utgaatt
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: skedulert-utgatt-model
            envVarPrefix: DB