apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-bruker-api-writer
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  replicas:
    min: 1
    max: 2
  kafka:
    pool: nav-dev
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-notifikasjon-bruker-api
  filesFrom:
    - secret: sqeletor-notifikasjon-bruker-api-v2-1136d046
      mountPath: /var/run/secrets/nais.io/sqlcertificate

---
# https://nav-it.slack.com/archives/C5KUST8N6/p1680085706741319
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notifikasjon-bruker-api-writer-db
  namespace: fager
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 100.71.2.153/32
  podSelector:
    matchLabels:
      app: notifikasjon-bruker-api-writer
  policyTypes:
    - Egress
