apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-dataprodukt
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    limits:
      memory: 512Mi
  liveness:
    path: /internal/alive
    initialDelay: 30
  readiness:
    path: /internal/ready
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  replicas:
    min: 1
    max: 1
  envFrom:
    - secret: notifikasjon-dataprodukt
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - name: notifikasjon-dataprodukt-v2
        type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: dataprodukt-model
            envVarPrefix: DB
