apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-bruker-api
  namespace: fager
  labels:
    team: fager
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
  ingresses:
    - https://ag-notifikasjon-bruker-api.intern.dev.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - name: notifikasjon-bruker-api-v2
        type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: bruker-model
            envVarPrefix: DB
            users:
              - name: bruker-api-kafka-user
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
        - application: tiltaksgjennomforing
          namespace: arbeidsgiver
        - application: aareg-innsyn-arbeidsgiver
          namespace: arbeidsforhold
        - application: min-ia
          namespace: pia
        - application: presenterte-kandidater
          namespace: toi
    outbound:
      rules:
        - application: arbeidsgiver-altinn-tilganger
      external:
        - host: fakedings.intern.dev.nav.no # fakedings login
        - host: ereg-services-q1.dev-fss-pub.nais.io # ereg brukes i bruker-api
  envFrom:
    - secret: notifikasjon-bruker-api-secrets

