apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-hendelse-transformer
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    limits:
      memory: 512Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-dev