apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-ekstern-varsling
  namespace: fager
  labels:
    team: fager
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:serviceowner/notifications.create"
  accessPolicy:
    outbound:
      rules:
        - application: altinn-varsel-firewall
      external:
        - host: platform.altinn.no
  gcp:
    sqlInstances:
      - name: notifikasjon-ekstern-varsling-v2
        type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: ekstern-varsling-model
            envVarPrefix: DB
  env:
    - name: ALTINN_3_API_BASE_URL
      value: https://platform.altinn.no
  envFrom:
    - secret: altinn-basic-ws
