apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-replay-validator
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 10
    max: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-prod