apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-replay-validator
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 345m
      memory: 712Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/alive
    initialDelay: 60
  readiness:
    path: /internal/ready
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  replicas:
    min: 1
    max: 1
  kafka:
    pool: nav-prod