apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  ingresses:
    - https://ag-notifikasjon-produsent-api.intern.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 2
    max: 8
  prometheus:
    enabled: true
    path: /internal/metrics
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: prod-fss

        - application: tiltak-notifikasjon
          namespace: team-tiltak
          cluster: prod-gcp

        - application: permitteringsmelding-notifikasjon
          namespace: permittering-og-nedbemanning
          cluster: prod-gcp

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-fss

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-gcp

        - application: fritakagp
          namespace: helsearbeidsgiver
          cluster: prod-gcp

        - application: toi-arbeidsgiver-notifikasjon
          namespace: toi
          cluster: prod-gcp

        - application: im-notifikasjon
          namespace: helsearbeidsgiver
          cluster: prod-gcp

        - application: hag-admin
          namespace: helsearbeidsgiver
          cluster: prod-gcp

        - application: saas-proxy
          namespace: teamcrm
          cluster: prod-gcp

        - application: salesforce
          namespace: teamcrm
          cluster: prod-external

        - application: yrkesskade-melding-mottak
          namespace: yrkesskade
          cluster: prod-gcp

        - application: fpinntektsmelding
          namespace: teamforeldrepenger
          cluster: prod-gcp

  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: produsent-model
            envVarPrefix: DB
        autoBackupHour: 1
        maintenance:
          hour: 3
  env:
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
  envFrom:
    - secret: notifikasjon-produsent-api-secrets
