apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-manuelt-vedlikehold
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  liveness:
    path: /internal/alive
    initialDelay: 60
  readiness:
    path: /internal/ready
    initialDelay: 60
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  kafka:
    pool: nav-prod