apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: fager
  labels:
    team: fager
  annotations:
    texas.nais.io/enabled: "true"
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 40m
      memory: 704Mi
    limits:
      memory: 1024Mi
  ingresses:
    - https://ag-notifikasjon-produsent-api.intern.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  replicas:
    min: 2
    max: 8
  accessPolicy:
    inbound:
      rules:
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: prod-fss

        - application: tiltak-notifikasjon
          namespace: team-tiltak
          cluster: prod-gcp

        - application: permitteringsskjema-api
          namespace: permittering-og-nedbemanning
          cluster: prod-gcp

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-fss

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: prod-gcp

        - application: fritakagp
          namespace: helsearbeidsgiver
          cluster: prod-gcp

        - application: toi-arbeidsgiver-notifikasjon
          namespace: toi
          cluster: prod-gcp

        - application: im-notifikasjon
          namespace: helsearbeidsgiver
          cluster: prod-gcp

        - application: hag-admin
          namespace: helsearbeidsgiver
          cluster: prod-gcp

        - application: saas-proxy
          namespace: teamcrm
          cluster: prod-gcp

        - application: salesforce
          namespace: teamcrm
          cluster: prod-external

        - application: yrkesskade-melding-mottak
          namespace: yrkesskade
          cluster: prod-gcp

        - application: yrkesskade-saksbehandling-backend
          namespace: yrkesskade
          cluster: prod-gcp

        - application: fpinntektsmelding
          namespace: teamforeldrepenger
          cluster: prod-gcp

        - application: k9-inntektsmelding
          namespace: k9saksbehandling
          cluster: prod-gcp
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - name: notifikasjon-produsent-api-v2
        type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: produsent-model
            envVarPrefix: DB
  envFrom:
    - secret: notifikasjon-produsent-api-secrets
