apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-dataprodukt
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  envFrom:
    - secret: notifikasjon-dataprodukt
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - name: notifikasjon-dataprodukt-v2
        type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: dataprodukt-model
            envVarPrefix: DB
