apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-skedulert-utgaatt
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      memory: 1024Mi
  replicas:
    disableAutoScaling: true
    min: 10
    max: 10
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: skedulert-utgatt-model
            envVarPrefix: DB