apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-kafka-bq
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1024Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
  kafka:
    pool: nav-prod
  gcp:
    bigQueryDatasets:
      - name: debughendelse
        permission: READWRITE
  env:
    - name: BIGQUERY_DATASET_ID
      value: debughendelse 
    - name: BIGQUERY_TABLE_NAME
      value: notifikasjon
