name: "Platform: deploy kafka-manager prod"
on:
  push:
    branches:
      - main
    paths:
      - app/nais/prod-gcp-kafka-manager.yaml
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        name: "prod-gcp: deploy kafka-manager"
        env:
          CLUSTER: prod-gcp
          RESOURCE: app/nais/prod-gcp-kafka-manager.yaml
