name: "Platform: deploy dev manual"
on:
  workflow_dispatch:

jobs:
  dev-deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster:
          - dev-gcp
        app:
          - bruker-api
          - bruker-api-writer
          - produsent-api
          - kafka-reaper
          - ekstern-varsling
          - replay-validator
          - kafka-backup
          - skedulert-utgaatt
          - skedulert-harddelete
          - skedulert-paaminnelse
          - dataprodukt
          - kafka-bq
          #- manuelt-vedlikehold
    steps:
      - uses: actions/checkout@v4
      - name: NAIS login
        uses: nais/login@v0
        id: login
        with:
          team: fager
      - uses: nais/deploy/actions/deploy@v2
        name: "${{ matrix.cluster }}: deploy ${{ matrix.app }}"
        env:
          VAR: image=${{ steps.login.outputs.registry }}/arbeidsgiver-notifikasjon-produsent-api:${{ github.sha }}
          REF: ${{ github.sha }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: app/nais/${{ matrix.cluster }}-${{ matrix.app }}.yaml
